{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin-ha.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "jellyfin-ha.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
{{- end }}
